### ISSUE TITLE
Entities periodically become unavailable 

### ISSUE THREAD

**Issue by BenGlossop09** [schmittx/home-assistant-eero#106]
Having looked at other tickets I have not seen this issue covered elsewhere. 

Entities become unavailable periodically, it looks like the result of a timeout. Frequency was several times per hour but has reduced to several times per day after reducing quantity of tracked devices. Each occurrence lasts approximately 5 minutes then the entities update successfully. 

I've found reducing the number of devices/entries which are tracked reduces the frequency of entities becoming unavailable. Is there a known number of devices or entities which works best for this integration? 

Logs show:
`This error originated from a custom integration.

Logger: custom_components.eero
Source: helpers/update_coordinator.py:388
integration: eero (documentation, issues)
First occurred: 1 December 2024 at 17:09:06 (16 occurrences)
Last logged: 17:27:52

Timeout fetching Eero (Ben Glossop) data`

And;
`This error originated from a custom integration.

Logger: custom_components.eero
Source: helpers/update_coordinator.py:382
integration: eero (documentation, issues)
First occurred: 16:32:41 (1 occurrences)
Last logged: 16:32:41

Unexpected error fetching Eero (Ben Glossop) data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/__init__.py", line 195, in async_update_data
    return await hass.async_add_executor_job(api.update, conf_networks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/__init__.py", line 279, in update
    activity_data[resource][activity] = self.update_activity(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/__init__.py", line 316, in update_activity
    data = self.call(
           ^^^^^^^^^^
  File "/config/custom_components/eero/api/__init__.py", line 102, in call
    response = self.parse_response(response=response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/__init__.py", line 177, in parse_response
    code=meta.get("code"),
         ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by adamzeis** [comment]
Experiencing this as well, more often than not.

**Comment by eduardoribeiro** [comment]
This happens to me every time Home Assistant restarts... the integration seems to work just fine but all the entities are unavailable

**Comment by schmittx** [comment]
Is it the same error for everyone? Please post your logs, it helps to diagnose the problem.

**Comment by BenGlossop09** [comment]
To update, the frequency at which entities become unavailable has dramatically increased. I have made no configuration changes to the integration however I have updated to the latest version of home assistant OS and Core. 

Screenshot showing increased frequency:
![Screenshot_20241217-135555.png](https://github.com/user-attachments/assets/950b2397-145e-4bc4-930e-e07526c543ee)

**Comment by robdur94** [comment]
So I think there's an issue with the number of devices enabled, number of metrics being collected and the frequency. If I enable too many devices Eero starts limiting DNS requisitions so my guess it there's some rate limiting. I also have Advance Security enable so need to test with that turned off to see if. that or there's a rate limit on the API calls

**Comment by BenGlossop09** [comment]
I've reduced my entity count to 79, though it wasn't much higher before. I will see how much of an impact this has.

**Comment by schmittx** [comment]
I just pushed a new version [1.7.0](https://github.com/schmittx/home-assistant-eero/releases/tag/1.7.0) that should significantly improve the various bugs and error handling (but doesn't yet address rate limiting directly). Take a look and let me know know of any concerns or feedback.

**Comment by schmittx** [comment]
Closing for now, please comment and/or re-open if this issue persists.
