### ISSUE TITLE
"Failed to set up" error on (most) every restart of Home Assistant

### ISSUE THREAD

**Issue by jeffalperin** [schmittx/home-assistant-eero#12]
I'm running Home Assistant OS 2021.5.5 and each time I restart, the Eero custom integration fails with the following errors in the log:
++++

Logger: homeassistant.config_entries             Source: custom_components/eero/__init__.py:306                                                   Integration: eero                                            (documentation,                               issues)                                                                                     First occurred:                   May 28, 2021, 2:21:10 PM                   (1 occurrences)                               Last logged:             May 28, 2021, 2:21:10 PM           
 Error setting up entry Jeff Alperin for eero
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/eero/__init__.py", line 306, in async_setup_entry
    if any([eero.is_eero_beacon for network in coordinator.data.networks for eero in network.eeros]):
AttributeError: 'NoneType' object has no attribute 'networks'

```

Logger: custom_components.eero
Source: helpers/update_coordinator.py:186
Integration: eero (documentation, issues)
First occurred: May 28, 2021, 2:21:10 PM (1 occurrences)
Last logged: May 28, 2021, 2:21:10 PM
Timeout fetching Eero (Jeff Alperin) data

++++

If I delete the integration and then add it back in and re-configure it, it works fine -- until the next time I restart HA.

Any suggestions for addressing the issue?

--Jeff

**Comment by rjbudke** [comment]
I’m also having this exact same issue.

**Comment by Wolbyworld** [comment]
Same issue.

`Home Assistant OS 6.1
core-2021.6.6`

**Comment by JamesDenby** [comment]
I have this same issue and error

**Comment by coleya** [comment]
I am experiencing this bug as well on home assistant version 2021.9.6 and integration version 1.1.3.

**Comment by coleya** [comment]
I turned on the extra logging option after a reboot when the configflow was working and I'm not certain if this showed up because of it or if I just didn't notice before but another error shows up in addition to the one originally reported in the issue:
```
This error originated from a custom integration.

Logger: custom_components.eero
Source: custom_components/eero/api/__init__.py:111
Integration: eero (documentation, issues)
First occurred: 1:12:54 AM (1 occurrences)
Last logged: 1:12:54 AM

Unexpected error fetching Eero (ColeYa) data: Expecting value: line 2 column 1 (char 1)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/eero/__init__.py", line 176, in async_update_data
    return await hass.async_add_executor_job(api.update)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eero/api/__init__.py", line 141, in update
    network_data = self.call(method="get", url=network["url"])
  File "/config/custom_components/eero/api/__init__.py", line 60, in call
    response = self.parse_response(response)
  File "/config/custom_components/eero/api/__init__.py", line 111, in parse_response
    data = json.loads(response.text)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by Wolbyworld** [comment]
Still happening afte rthe last update

**Comment by ab623** [comment]
Mine is causing this error as soon as I finish the setup of the eero integration.

**Comment by cjs28** [comment]
I noticed that when I just configure options in the "Select network resources" section of the config and skip any settings in "Select activity metrics" this integration works great as just a device tracker. As soon as I select any option within the "Select activity metrics" configuration screen that is when the integration starts to fail with these error messages.


`ogger: aiohttp.server
Source: custom_components/eero/config_flow.py:233
Integration: eero (documentation, issues)
First occurred: 8:53:58 PM (3 occurrences)
Last logged: 9:09:26 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 192, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/eero/config_flow.py", line 225, in async_step_init
    return await self.async_step_networks()
  File "/config/custom_components/eero/config_flow.py", line 233, in async_step_networks
    conf_networks = [network.name_long for network in self.coordinator.data.networks if network.id in self.options.get(CONF_NETWORKS, self.data[CONF_NETWORKS])]
AttributeError: 'NoneType' object has no attribute 'networks'`


`Logger: homeassistant.config_entries
Source: custom_components/eero/__init__.py:306
Integration: eero (documentation, issues)
First occurred: 8:51:14 PM (4 occurrences)
Last logged: 9:10:47 PM

Error setting up entry Christopher Slagle for eero
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/eero/__init__.py", line 306, in async_setup_entry
    if any([eero.is_eero_beacon for network in coordinator.data.networks for eero in network.eeros]):
AttributeError: 'NoneType' object has no attribute 'networks'`

**Comment by amathews84** [comment]
I am getting this issue as well.  When I click Configure it says, "Config flow could not be loaded".  Here are the error logs:

```Logger: aiohttp.server
Source: custom_components/eero/config_flow.py:233
Integration: eero (documentation, issues)
First occurred: 9:10:20 PM (2 occurrences)
Last logged: 9:11:23 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 192, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/eero/config_flow.py", line 225, in async_step_init
    return await self.async_step_networks()
  File "/config/custom_components/eero/config_flow.py", line 233, in async_step_networks
    conf_networks = [network.name_long for network in self.coordinator.data.networks if network.id in self.options.get(CONF_NETWORKS, self.data[CONF_NETWORKS])]
AttributeError: 'NoneType' object has no attribute 'networks'
```


Another Error in the Logs:
````This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/eero/__init__.py:333
Integration: eero (documentation, issues)
First occurred: 9:07:03 PM (1 occurrences)
Last logged: 9:07:03 PM

Error setting up entry Alex Mathews for eero
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/eero/__init__.py", line 333, in async_setup_entry
    if any([eero.is_eero_beacon for network in coordinator.data.networks for eero in network.eeros]):
AttributeError: 'NoneType' object has no attribute 'networks'

**Comment by schmittx** [comment]
Let me know if you're still having problems with [1.2.0](https://github.com/schmittx/home-assistant-eero/releases/tag/1.2.0)
