### ISSUE TITLE
Can't select devices on setup in HA

### ISSUE THREAD

**Issue by thatvalis** [schmittx/home-assistant-eero#23]
Hi,

I get an error: "User input malformed" during setup when I try to check boxes.
It pops up on every step, but when I left the box unchecked I can continue.
It worked up until "devices" when the wired and wireless devices weren't added.
I can see all devices that is on my network, but when I select them to be added I get:
"User input malformed".
If I just click through without checking any boxes only the Eeros themselves gets added.

Is there an easy fix to this?
Seems checkboxes operate in an opposite manner.

**Comment by megakid** [comment]
I am getting the same thing on `1.1.3` and HA `core-2021.11.1`

**Comment by applegeeks** [comment]
+1 somehow of a similar error for me during startup/setup.
I get a "Unknown error occured".
This occurs whether I select any eero devices, wifi devices or none. 
All with the same result.
![image](https://user-images.githubusercontent.com/98582882/151629868-26c104b6-6b78-4f9b-a253-cac16f92ac1f.png)

> Log error from the HA server 
Logger: aiohttp.server
Source: custom_components/eero/config_flow.py:127 
Integration: eero (documentation, issues) 
First occurred: January 28, 2022, 10:53:01 PM (6 occurrences) 
Last logged: 8:20:17 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/eero/config_flow.py", line 127, in async_step_resources
    if network.id == self.user_input[CONF_NETWORKS][self.index]:

**Comment by hunleyd** [comment]
same error as @applegeeks here. 1.1.4 with HA 2022.5.5

**Comment by schmittx** [comment]
Let me know if you're still having problems with [1.2.0](https://github.com/schmittx/home-assistant-eero/releases/tag/1.2.0)
