### ISSUE TITLE
Fails to load after updating to Home Assistant Core 2023.5

### ISSUE THREAD

**Issue by pietrouk** [schmittx/home-assistant-eero#48]
These errors are in the logs

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/eero/config_flow.py:224
Integration: eero (documentation, issues)
First occurred: 09:39:47 (1 occurrences)
Last logged: 09:39:47

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 218, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 243, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/eero/config_flow.py", line 224, in async_step_init
    self.coordinator = self.hass.data[DOMAIN][self.config_entry.entry_id][DATA_COORDINATOR]
KeyError: 'eero'

Also:

Logger: homeassistant.config_entries
Source: loader.py:1045
First occurred: 08:27:19 (2 occurrences)
Last logged: 09:39:53

Error setting up entry Eero WiFi for eero
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eero/__init__.py", line 149, in async_setup_entry
    device_registry = await hass.helpers.device_registry.async_get_registry()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1045, in __getattr__
    value = getattr(self._module, attr)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'

**Comment by LostJen** [comment]
Same. Even a delete and readd fails.

**Comment by SinisterMedusa** [comment]
Exact same problem here.

**Comment by thayerfox** [comment]
This is the same as issue #41.

**Comment by michaelthompson1991** [comment]
Same problem here

**Comment by frasim** [comment]
Same problem for me too

**Comment by michaelthompson1991** [comment]
At least I’m not the only one!Sent from my iPhoneOn 4 May 2023, at 22:20, Francesco ***@***.***> wrote:﻿
Same problem for me too

**Comment by schmittx** [comment]
Fixed in [1.2](https://github.com/schmittx/home-assistant-eero/releases/tag/1.2.0).
