### ISSUE TITLE
Unable to login to the Eero account

### ISSUE THREAD

**Issue by OliverH77** [schmittx/home-assistant-eero#67]
I just installed the plugin, but it's not possible to log into the Eero account.
When trying to email, the message "Unknown error occurred" appears. If I try using the phone number on file, I'm supposed to enter the verification code. But none will be sent.

The email address is definitely correct.

Here is the log from HA:

`2023-08-31 07:46:50.127 ERROR (SyncWorker_3) [custom_components.eero.api] Exception raised, status code: 401, text: {'meta': {'code': 401, 'server_time': '2023-08-31T05:46:50.031Z', 'error': 'error.login.unknown'}}
2023-08-31 07:46:50.132 ERROR (MainThread) [custom_components.eero.config_flow] Status: 401, Error Message: error.login.unknown
2023-08-31 07:46:50.135 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 296, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 392, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/config_flow.py", line 77, in async_step_user
    self.user_input[CONF_USER_TOKEN] = self.response["user_token"]
                                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
`

**Comment by peppy6582** [comment]
Same

**Comment by schmittx** [comment]
What method do you use to log in to the Eero app? And, have you enabled the use of Amazon login (under account settings in Eero app)?

**Comment by OliverH77** [comment]
Do you mean that:

![image](https://github.com/schmittx/home-assistant-eero/assets/60742940/d2de6a7a-78b2-4502-b38a-5dd0ab7ff5ff)

?
Logged in with my Amazon Account.

**Comment by schmittx** [comment]
Yes, you're using Amazon login method which this integration does not support (see #17).
