### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by akeslo** [schmittx/home-assistant-eero#7]
![image](https://user-images.githubusercontent.com/3003773/111660785-ce65bf80-87e4-11eb-89ef-59fccd526df3.png)

Logger: aiohttp.server
Source: custom_components/eero/config_flow.py:127
First occurred: 12:20:23 PM (4 occurrences)
Last logged: 12:23:57 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 150, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 158, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 216, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/eero/config_flow.py", line 127, in async_step_resources
    if network.id == self.user_input[CONF_NETWORKS][self.index]:
IndexError: list index out of range

**Comment by schmittx** [comment]
Sorry for the slow response, are you still experiencing this error?

**Comment by martindinicolino** [comment]
I'm getting the same error, but when i'm trying to sign in to my Eero account (both with my associated phone number and email address; i do not have an amazon account associated to my eero profile, so i am not using that login method);

any chance you might remember what you did to get past that?

**Comment by applegeeks** [comment]
> I'm getting the same error, but when i'm trying to sign in to my Eero account (both with my associated phone number and email address; i do not have an amazon account associated to my eero profile, so i am not using that login method);
> 
> any chance you might remember what you did to get past that?

to be honest, i've been trying to get past that same error for a while but eventually gave up.
Ended up using the integration that this was orginally based from.
https://github.com/jrlucier/eero_tracker
since I only needed the device tracking functionality mainly.
worth a shot if that's all you need to do as well.
