### ISSUE TITLE
Error w/ getting firmware details

### ISSUE THREAD

**Issue by stuartparmenter** [schmittx/home-assistant-eero#86]
I expect the root of this is that I’m running w/ eero beta, but wanted to flag.  Let me know if I can help debug further.

Logger: homeassistant.components.update
Source: helpers/entity_platform.py:600
integration: Update (documentation, issues)
First occurred: June 30, 2024 at 2:41:18 PM (13 occurrences)
Last logged: 10:20:16 AM

Error adding entity None for domain update with platform eero
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 600, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 831, in _async_add_entity
    supported_features=entity.supported_features,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/update.py", line 124, in supported_features
    if self.resource.target_firmware.features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/eero.py", line 139, in target_firmware
    return self.network.target_firmware
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/network.py", line 545, in target_firmware
    return EeroFirmware(self.data.get("updates", {}).get("release_notes", {}).get("target", {}))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by schmittx** [comment]
Closing for now, please comment if you're still experiencing this concern.
