### ISSUE TITLE
Finished fetching Eero (Name) data in 10.002 seconds (success: False)... Timeout & AttributeError

### ISSUE THREAD

**Issue by addshore** [schmittx/home-assistant-eero#88]
I reloaded HA today, and the integration will not come back up properly.

Using V `1.5.0`

![image](https://github.com/schmittx/home-assistant-eero/assets/3308769/11235157-710c-4d4c-ad5e-71debd362661)

Logs look like this

```
2024-07-09 20:22:49.281 DEBUG (SyncWorker_0) [custom_components.eero.api] Calling API with method: GET and URL: /2.2/account
2024-07-09 20:22:50.111 DEBUG (SyncWorker_0) [custom_components.eero.api] Calling API with method: GET and URL: /2.2/networks/<networkid>
2024-07-09 20:22:59.281 ERROR (MainThread) [custom_components.eero] Timeout fetching Eero (Someones Name) data
2024-07-09 20:22:59.282 DEBUG (MainThread) [custom_components.eero] Finished fetching Eero (Someones Name) data in 10.002 seconds (success: False)
2024-07-09 20:22:59.283 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Someones Name for eero
File "/config/custom_components/eero/__init__.py", line 320, in async_setup_entry
if any([eero.is_eero_beacon for network in coordinator.data.networks for eero in network.eeros]):
```

This looks similar to https://github.com/schmittx/home-assistant-eero/issues/61 in the fact that it might just be a timeout?

```
This error originated from a custom integration.

Logger: custom_components.eero
Source: helpers/update_coordinator.py:318
integration: eero (documentation, issues)
First occurred: 20:10:27 (4 occurrences)
Last logged: 20:22:59

Timeout fetching Eero (Someones Name) data
```

```
Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 20:10:27 (4 occurrences)
Last logged: 20:22:59

Error setting up entry Someones Name for eero
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/__init__.py", line 320, in async_setup_entry
    if any([eero.is_eero_beacon for network in coordinator.data.networks for eero in network.eeros]):
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'networks'
```

**Comment by pressurejets** [comment]
i have the same problem

**Comment by matthewdias** [comment]
Seems like something's up on eero's end https://www.reddit.com/r/amazoneero/comments/1dz9fkr/eero_outage/

**Comment by mikefrantz** [comment]
I have the same problem that just started today. July 9th

**Comment by mikefrantz** [comment]
Here is my error logs.
![IMG_1723](https://github.com/schmittx/home-assistant-eero/assets/117596264/e863343a-000a-479b-85ff-43c7325218b1)

**Comment by matthewdias** [comment]
Seems to be back for me, at least for now.

**Comment by pressurejets** [comment]
thank you for the heads up yes back up and working.

**Comment by matthewdias** [comment]
ok now it's properly back. can probably close out this ticket as it's not an issue with this library

**Comment by addshore** [comment]
Yup, hitting reload just now has made the integration come back online :)
